
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication4.JavaApplication4;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PRATAP KUMAR
 */
public class register extends javax.swing.JFrame {

    Connection conn = null;

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        conn = JavaApplication4.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        emailTf = new javax.swing.JTextField();
        regpassTf = new javax.swing.JTextField();
        regBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        phoneTf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 140, 110, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("EMAIL ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 190, 140, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 310, 190, 30);

        nameTf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });
        getContentPane().add(nameTf);
        nameTf.setBounds(450, 140, 200, 30);

        emailTf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(emailTf);
        emailTf.setBounds(450, 190, 200, 35);

        regpassTf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(regpassTf);
        regpassTf.setBounds(450, 310, 200, 30);

        regBtn.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        regBtn.setText("Register");
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regBtn);
        regBtn.setBounds(290, 400, 220, 37);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setText("PHONE NUMBER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 250, 230, 30);

        phoneTf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(phoneTf);
        phoneTf.setBounds(450, 250, 200, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USER REGISTRATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 60, 790, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        String a = nameTf.getText();
        String b = emailTf.getText();
        String c = regpassTf.getText();
        String d = phoneTf.getText();

        Statement st;
        ResultSet rs;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/java_dbmovies", "root", "");
            st = conn.createStatement();
            int i = 0, y = 0, e = 0;
            st = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = executeQuery("select * from register");
            a = nameTf.getText();
            While(rs.next() && y == 0);
            {
                String p = rs.getString("name");
                a = nameTf.getText();
                System.out.println(p + "" + a);
            }
            System.out.println(e);
            st.executeUpdate("insert into register values('" + a + "','" + b + "','" + c + "','" + d + "');");
        } catch (Exception e) {
            System.out.println(e);
        }
        
        if ("".equals(a) && "".equals(b) && "".equals(c) && "".equals(d)) {
            JOptionPane.showMessageDialog(this, "please enter valid details");
        } else {

            try {
                Statement s = conn.createStatement();
                String s1 = ("insert into register values('" + a + "','" + b + "','" + c + "','" + d + "');");
                System.out.println("success");
                s.executeUpdate(s1);
            } catch (SQLException e) {
                Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, e);
            }

            this.setVisible(false);
            new login().setVisible(true);

    }//GEN-LAST:event_regBtnActionPerformed
}

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTf;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JButton regBtn;
    private javax.swing.JTextField regpassTf;
    // End of variables declaration//GEN-END:variables

    private ResultSet executeQuery(String select__from_register) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    private void While(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
}
